import {
  FileText,
  ShieldCheck,
  UserCheck,
  BookOpen,
  ClipboardList,
  Download,
  FileCheck,
  Users,
  Scale,
  HeartHandshake,
  Info,
  Lock,
  CheckCircle2,
  XCircle,
  Flag,
  Trophy,
  Medal,
  Calendar,
  Clock,
  MapPin,
  ExternalLink,
  Link2,
  BarChart3,
  Ticket,
  Megaphone,
  Image,
  type LucideIcon,
} from "lucide-react";

/** Iconos vectoriales disponibles para botones, documentos y estados (editables desde administración). */
export const LOPIVI_ICONS: Record<string, LucideIcon> = {
  FileText,
  ShieldCheck,
  UserCheck,
  BookOpen,
  ClipboardList,
  Download,
  FileCheck,
  Users,
  Scale,
  HeartHandshake,
  Info,
  Lock,
  CheckCircle2,
  XCircle,
  Flag,
  Trophy,
  Medal,
  Calendar,
  Clock,
  MapPin,
  ExternalLink,
  Link2,
  BarChart3,
  Ticket,
  Megaphone,
  Image,
};

export const LOPIVI_ICON_NAMES = Object.keys(LOPIVI_ICONS);

export function lopiviIcon(name: string | null | undefined): LucideIcon {
  return LOPIVI_ICONS[name ?? ""] ?? FileText;
}
